### ISSUE TITLE
Resize .svg folder icons to 22x22, 24x24, 48x48 and 64x64.

### ISSUE THREAD

**Issue by tansiret** [mercode-org/papirus-mer-icon-theme#1]
I have made custom folder icons and wanna replace them with folder-blue. I have made custom folder icons in 32x32 size, in both 32x32 and MerPlaces folders. Can you resize those icons in the MerPlaces folder to 22x22, 24x24, 48x48 and 64x64?

**Comment by mkg20001** [comment]
A script should do that? Which files exactly

**Comment by tansiret** [comment]
> A script should do that? Which files exactly

All svg files are in MerPlaces folder.
